/**
 * The only module in `src/` that knows D1 exists.
 *
 * Pages call the functions here and get plain objects back. That boundary is not decoration: on
 * the free tier a Worker invocation may issue 50 subrequests, and a page that queries in a loop
 * over its stations blows through that on a city like Sofia (283 devices). Everything below
 * aggregates in SQL and returns in a fixed, small number of queries — a city page is three, a
 * station page is three, regardless of how many sensors are involved.
 *
 * Absent is not zero. A column the ETL could not fill is NULL here and stays `null` all the way to
 * the renderer, which draws nothing rather than drawing a measurement of zero.
 */

import { env } from "cloudflare:workers";
import { slug, type SignalKey } from "./site";

/** `Env` is generated by `wrangler types` from wrangler.jsonc — rerun it when a binding changes. */
const DB = () => env.DB;

// ── row shapes ──────────────────────────────────────────────────────────────

export interface CityRow {
  id: number;
  country_id: number;
  /** Joined in from `countries`, so a page still reads `row.country` and nothing downstream moved. */
  country: string;
  country_slug: string;
  slug: string;
  name: string;
  lat: number;
  lon: number;
  rank: number;
  station_count: number;
  pm25_median: number | null;
  comfort: number | null;
  worst_signal: SignalKey | null;
  signals_json: string | null;
  /** The readings the scores came from, in their own units. A page prints these, not the scores. */
  readings_json: string | null;
  divergence: number | null;
  updated_at: string | null;
  indexable: number;
}

export interface StationRow {
  id: number;
  lat: number;
  lon: number;
  city_id: number | null;
  distance_km: number | null;
  sensor_type: string | null;
  first_seen: string | null;
  last_seen: string | null;
  pm25: number | null;
  pm10: number | null;
  pm25_24h: number | null;
  divergence: number | null;
  model_weight: number | null;
  merged_pm25: number | null;
  history_days: number;
  indexable: number;
}

export interface DayPoint {
  day: string;
  comfort: number | null;
  pm25: number | null;
  temp: number | null;
  uv: number | null;
}

/** The fourteen readings as the ETL stored them. Signals with no data are simply absent. */
export type Signals = Partial<Record<SignalKey, number>>;

export function parseSignals(json: string | null): Signals {
  if (!json) return {};
  try {
    const raw = JSON.parse(json) as Record<string, unknown>;
    const out: Signals = {};
    for (const [k, v] of Object.entries(raw)) {
      if (typeof v === "number" && Number.isFinite(v)) out[k as SignalKey] = v;
    }
    return out;
  } catch {
    // A malformed blob is a bug in the ETL, not a reason to 500 a page that has everything else.
    return {};
  }
}

// ── countries ───────────────────────────────────────────────────────────────

export interface CountryRow {
  id: number;
  slug: string;
  name: string;
  iso: string | null;
  city_count: number;
  station_count: number;
  comfort: number | null;
  pm25_median: number | null;
  best_city_id: number | null;
  worst_city_id: number | null;
  updated_at: string | null;
  indexable: number;
}

export async function getCountry(countrySlug: string): Promise<CountryRow | null> {
  return await DB()
    .prepare("SELECT * FROM countries WHERE slug = ?1")
    .bind(slug(countrySlug))
    .first<CountryRow>();
}

/**
 * Every country, densest first.
 *
 * 156 rows with their totals already rolled up — the reason the countries table exists. Computing
 * these with a GROUP BY over ten thousand cities on every request would work at this size and be
 * the same mistake as querying in a loop, just better hidden.
 */
export async function listCountries(): Promise<CountryRow[]> {
  const { results } = await DB()
    .prepare("SELECT * FROM countries ORDER BY station_count DESC, city_count DESC, name")
    .all<CountryRow>();
  return results ?? [];
}

/** A country's cities. Ordered by comfort where it is known, then by population rank. */
export async function getCitiesInCountry(countryId: number, limit = 200): Promise<CityRow[]> {
  const { results } = await DB()
    .prepare(
      `SELECT c.*, co.slug AS country_slug, co.name AS country
         FROM cities c JOIN countries co ON co.id = c.country_id
        WHERE c.country_id = ?1
        ORDER BY (c.station_count = 0), (c.comfort IS NULL), c.comfort DESC, c.rank
        LIMIT ?2`,
    )
    .bind(countryId, limit)
    .all<CityRow>();
  return results ?? [];
}

// ── cities ──────────────────────────────────────────────────────────────────

/**
 * Every city query selects through this.
 *
 * `country` and `country_slug` are joined in rather than stored on the row, which is the whole
 * point of the countries table: there is one spelling of "Turkey" in the database and one place
 * that owns it. The join is an indexed integer key and adds no query — the city page still costs
 * the same four round trips it always did.
 */
const CITY_SELECT = `
  SELECT c.*, co.slug AS country_slug, co.name AS country
    FROM cities c JOIN countries co ON co.id = c.country_id`;

export async function getCity(countrySlug: string, citySlug: string): Promise<CityRow | null> {
  return await DB()
    .prepare(`${CITY_SELECT} WHERE co.slug = ?1 AND c.slug = ?2`)
    .bind(slug(countrySlug), slug(citySlug))
    .first<CityRow>();
}

export async function getCityById(id: number): Promise<CityRow | null> {
  return await DB().prepare(`${CITY_SELECT} WHERE c.id = ?1`).bind(id).first<CityRow>();
}

/** Thirty days of daily aggregates, oldest first — the shape the chart wants. */
export async function getCityHistory(cityId: number, days = 30): Promise<DayPoint[]> {
  const { results } = await DB()
    .prepare(
      `SELECT day, comfort, pm25, temp, uv
         FROM city_daily
        WHERE city_id = ?1
        ORDER BY day DESC
        LIMIT ?2`,
    )
    .bind(cityId, days)
    .all<DayPoint>();
  return (results ?? []).reverse();
}

/**
 * Cities near a point, for the "nearby" rail. Bounded by a lat/lon box first so SQLite can use
 * the geo index; the exact distance ordering happens on the handful of rows that survive.
 */
export async function getNearbyCities(
  lat: number,
  lon: number,
  degrees = 2,
  limit = 6,
  excludeId?: number,
): Promise<CityRow[]> {
  const { results } = await DB()
    .prepare(
      `${CITY_SELECT}
        WHERE c.lat BETWEEN ?1 - ?3 AND ?1 + ?3
          AND c.lon BETWEEN ?2 - ?3 AND ?2 + ?3
          AND c.id != ?5
        ORDER BY (c.lat - ?1) * (c.lat - ?1) + (c.lon - ?2) * (c.lon - ?2)
        LIMIT ?4`,
    )
    .bind(lat, lon, degrees, limit, excludeId ?? -1)
    .all<CityRow>();
  return results ?? [];
}

/** Prefix search for the city picker. SQL, not the WASM cities database — that stays in the ETL. */
export async function searchCities(query: string, limit = 8): Promise<CityRow[]> {
  const q = query.trim();
  if (q.length < 2) return [];
  const { results } = await DB()
    .prepare(
      `${CITY_SELECT}
        WHERE c.name LIKE ?1 ESCAPE '\\'
        ORDER BY c.rank
        LIMIT ?2`,
    )
    .bind(`${q.replace(/[%_\\]/g, "\\$&")}%`, limit)
    .all<CityRow>();
  return results ?? [];
}

/**
 * Every city with a device, best comfort first — the ranking page.
 *
 * Deliberately not `getCityAggregates`: that one feeds the map and must stay lean, and adding the
 * signal blob to it would put ten thousand copies of a JSON string into a GeoJSON response for the
 * sake of a list nobody is looking at from the map.
 */
export async function getRankedCities(limit = 200): Promise<CityRow[]> {
  const { results } = await DB()
    .prepare(
      `${CITY_SELECT}
        WHERE c.comfort IS NOT NULL AND c.station_count > 0
        ORDER BY c.comfort DESC, c.station_count DESC
        LIMIT ?1`,
    )
    .bind(limit)
    .all<CityRow>();
  return results ?? [];
}

/** How many cities have a device at all — the total behind a truncated ranking. */
export async function countCitiesWithSensors(): Promise<number> {
  const row = await DB()
    .prepare("SELECT COUNT(*) AS n FROM cities WHERE comfort IS NOT NULL AND station_count > 0")
    .first<{ n: number }>();
  return row?.n ?? 0;
}

/** Best and worst comfort today, for the home page. One query, not two passes. */
export async function getComfortExtremes(limit = 6): Promise<{ best: CityRow[]; worst: CityRow[] }> {
  const [best, worst] = await DB().batch<CityRow>([
    DB()
      .prepare(
        `${CITY_SELECT}
          WHERE c.comfort IS NOT NULL AND c.station_count > 0
          ORDER BY c.comfort DESC LIMIT ?1`,
      )
      .bind(limit),
    DB()
      .prepare(
        `${CITY_SELECT}
          WHERE c.comfort IS NOT NULL AND c.station_count > 0
          ORDER BY c.comfort ASC LIMIT ?1`,
      )
      .bind(limit),
  ]);
  return { best: best.results ?? [], worst: worst.results ?? [] };
}

// ── stations ────────────────────────────────────────────────────────────────

export async function getStation(id: number): Promise<StationRow | null> {
  return await DB().prepare("SELECT * FROM stations WHERE id = ?1").bind(id).first<StationRow>();
}

/** The devices a city's numbers were computed from, worst reading first. */
export async function getStationsForCity(cityId: number, limit = 60): Promise<StationRow[]> {
  const { results } = await DB()
    .prepare(
      `SELECT * FROM stations
        WHERE city_id = ?1
        ORDER BY (last_seen IS NULL), pm25 DESC
        LIMIT ?2`,
    )
    .bind(cityId, limit)
    .all<StationRow>();
  return results ?? [];
}

export async function getStationHistory(
  stationId: number,
  days = 30,
): Promise<{ day: string; pm25: number | null; pm10: number | null }[]> {
  const { results } = await DB()
    .prepare(
      `SELECT day, pm25, pm10 FROM readings_daily
        WHERE station_id = ?1
        ORDER BY day DESC LIMIT ?2`,
    )
    .bind(stationId, days)
    .all<{ day: string; pm25: number | null; pm10: number | null }>();
  return (results ?? []).reverse();
}

/**
 * The median a station page compares itself against. Computed in SQL over the city's devices so
 * the page does not have to fetch them all just to sort a list — SQLite has no MEDIAN, hence the
 * offset trick.
 */
export async function getCityPmMedian(cityId: number): Promise<number | null> {
  const row = await DB()
    .prepare(
      `SELECT AVG(pm25) AS median FROM (
         SELECT pm25 FROM stations
          WHERE city_id = ?1 AND pm25 IS NOT NULL
          ORDER BY pm25
          LIMIT 2 - (SELECT COUNT(*) FROM stations WHERE city_id = ?1 AND pm25 IS NOT NULL) % 2
         OFFSET (SELECT (COUNT(*) - 1) / 2 FROM stations WHERE city_id = ?1 AND pm25 IS NOT NULL)
       )`,
    )
    .bind(cityId)
    .first<{ median: number | null }>();
  return row?.median ?? null;
}

// ── map layers ──────────────────────────────────────────────────────────────

/** Zoom < 8: one dot per city, sized by device count. Only cities that actually have devices. */
export async function getCityAggregates(): Promise<
  { id: number; name: string; country_slug: string; slug: string; lat: number; lon: number; station_count: number; pm25_median: number | null; comfort: number | null }[]
> {
  const { results } = await DB()
    .prepare(
      `SELECT c.id, c.name, co.slug AS country_slug, c.slug, c.lat, c.lon,
              c.station_count, c.pm25_median, c.comfort
         FROM cities c JOIN countries co ON co.id = c.country_id
        WHERE c.station_count > 0`,
    )
    .all<any>();
  return results ?? [];
}

/**
 * Zoom >= 8: the devices themselves. `bbox` is honoured when given; without it the whole set comes
 * back, which at ~9 000 rows is a 400 KB response the edge caches — cheaper than a query per pan.
 */
export async function getStationPoints(
  bbox?: [number, number, number, number],
): Promise<{ id: number; lat: number; lon: number; pm25: number | null; last_seen: string | null; city_id: number | null }[]> {
  const base = `SELECT id, lat, lon, pm25, last_seen, city_id FROM stations`;
  const stmt = bbox
    ? DB()
        .prepare(`${base} WHERE lat BETWEEN ?1 AND ?3 AND lon BETWEEN ?2 AND ?4`)
        .bind(bbox[1], bbox[0], bbox[3], bbox[2])
    : DB().prepare(base);
  const { results } = await stmt.all<any>();
  return results ?? [];
}

// ── sitemap ─────────────────────────────────────────────────────────────────

export interface SitemapCounts {
  cities: number;
  citiesIndexable: number;
  stations: number;
  stationsIndexable: number;
}

/** Both totals, so the sitemap route can log what it dropped instead of truncating in silence. */
export async function getSitemapCounts(): Promise<SitemapCounts> {
  const row = await DB()
    .prepare(
      `SELECT
         (SELECT COUNT(*) FROM cities)                      AS cities,
         (SELECT COUNT(*) FROM cities   WHERE indexable = 1) AS citiesIndexable,
         (SELECT COUNT(*) FROM stations)                     AS stations,
         (SELECT COUNT(*) FROM stations WHERE indexable = 1) AS stationsIndexable`,
    )
    .first<SitemapCounts>();
  return row ?? { cities: 0, citiesIndexable: 0, stations: 0, stationsIndexable: 0 };
}

export async function listIndexableCities(
  offset: number,
  limit: number,
): Promise<{ country_slug: string; slug: string; updated_at: string | null }[]> {
  const { results } = await DB()
    .prepare(
      `SELECT co.slug AS country_slug, c.slug, c.updated_at
         FROM cities c JOIN countries co ON co.id = c.country_id
        WHERE c.indexable = 1 ORDER BY c.id LIMIT ?1 OFFSET ?2`,
    )
    .bind(limit, offset)
    .all<any>();
  return results ?? [];
}

export async function listIndexableStations(
  offset: number,
  limit: number,
): Promise<{ id: number; country_slug: string; slug: string; last_seen: string | null }[]> {
  const { results } = await DB()
    .prepare(
      `SELECT s.id, co.slug AS country_slug, c.slug, s.last_seen
         FROM stations s
         JOIN cities c    ON c.id  = s.city_id
         JOIN countries co ON co.id = c.country_id
        WHERE s.indexable = 1 ORDER BY s.id LIMIT ?1 OFFSET ?2`,
    )
    .bind(limit, offset)
    .all<any>();
  return results ?? [];
}

// ── freshness ───────────────────────────────────────────────────────────────

/**
 * When the data was last refreshed. A page that is showing yesterday's numbers should say so
 * rather than imply it is live — the product's entire claim is about what is true right now.
 */
export async function getLastIngest(): Promise<Date | null> {
  const row = await DB()
    .prepare("SELECT value FROM meta WHERE key = 'last_ingest_at'")
    .first<{ value: string }>();
  const t = row?.value ? Date.parse(row.value) : NaN;
  return Number.isFinite(t) ? new Date(t) : null;
}
