/**
 * The only module in `src/` that knows D1 exists.
 *
 * Pages call the functions here and get plain objects back. That boundary is not decoration: on
 * the free tier a Worker invocation may issue 50 subrequests, and a page that queries in a loop
 * over its stations blows through that on a city like Sofia (283 devices). Everything below
 * aggregates in SQL and returns in a fixed, small number of queries — a city page is three, a
 * station page is three, regardless of how many sensors are involved.
 *
 * Absent is not zero. A column the ETL could not fill is NULL here and stays `null` all the way to
 * the renderer, which draws nothing rather than drawing a measurement of zero.
 */

import { env } from "cloudflare:workers";
import { paths, slug, type SignalKey } from "./site";

/** `Env` is generated by `wrangler types` from wrangler.jsonc — rerun it when a binding changes. */
const DB = () => env.DB;

// ── row shapes ──────────────────────────────────────────────────────────────

export interface CityRow {
  id: number;
  country_id: number;
  /** Joined in from `countries`, so a page still reads `row.country` and nothing downstream moved. */
  country: string;
  country_slug: string;
  slug: string;
  name: string;
  lat: number;
  lon: number;
  rank: number;
  station_count: number;
  pm25_median: number | null;
  comfort: number | null;
  worst_signal: SignalKey | null;
  signals_json: string | null;
  /** The readings the scores came from, in their own units. A page prints these, not the scores. */
  readings_json: string | null;
  divergence: number | null;
  updated_at: string | null;
  indexable: number;
}

export interface StationRow {
  id: number;
  lat: number;
  lon: number;
  city_id: number | null;
  distance_km: number | null;
  sensor_type: string | null;
  first_seen: string | null;
  last_seen: string | null;
  pm25: number | null;
  pm10: number | null;
  pm25_24h: number | null;
  divergence: number | null;
  model_weight: number | null;
  merged_pm25: number | null;
  history_days: number;
  indexable: number;
}

export interface DayPoint {
  day: string;
  comfort: number | null;
  pm25: number | null;
  temp: number | null;
  uv: number | null;
}

/** The fourteen readings as the ETL stored them. Signals with no data are simply absent. */
export type Signals = Partial<Record<SignalKey, number>>;

export function parseSignals(json: string | null): Signals {
  if (!json) return {};
  try {
    const raw = JSON.parse(json) as Record<string, unknown>;
    const out: Signals = {};
    for (const [k, v] of Object.entries(raw)) {
      if (typeof v === "number" && Number.isFinite(v)) out[k as SignalKey] = v;
    }
    return out;
  } catch {
    // A malformed blob is a bug in the ETL, not a reason to 500 a page that has everything else.
    return {};
  }
}

// ── countries ───────────────────────────────────────────────────────────────

export interface CountryRow {
  id: number;
  slug: string;
  name: string;
  iso: string | null;
  city_count: number;
  station_count: number;
  comfort: number | null;
  pm25_median: number | null;
  best_city_id: number | null;
  worst_city_id: number | null;
  updated_at: string | null;
  indexable: number;
}

export async function getCountry(countrySlug: string): Promise<CountryRow | null> {
  return await DB()
    .prepare("SELECT * FROM countries WHERE slug = ?1")
    .bind(slug(countrySlug))
    .first<CountryRow>();
}

/**
 * Every country, densest first.
 *
 * 156 rows with their totals already rolled up — the reason the countries table exists. Computing
 * these with a GROUP BY over ten thousand cities on every request would work at this size and be
 * the same mistake as querying in a loop, just better hidden.
 */
/**
 * The same idea as `CITY_SORTS`, for countries.
 *
 * `NULLS LAST` is spelled out on every order that can meet one. A country with no sensor has no
 * comfort and no median, and SQLite sorts NULL first — so "cleanest air" opened with a screen of
 * countries that have no reading at all, which is the opposite of what the heading promises.
 */
export const COUNTRY_SORTS = {
  sensors: { sql: "station_count DESC, city_count DESC, name", label: "Most sensors" },
  best: { sql: "comfort DESC NULLS LAST, station_count DESC", label: "Most comfortable" },
  worst: { sql: "comfort ASC NULLS LAST, station_count DESC", label: "Least comfortable" },
  cleanest: { sql: "pm25_median ASC NULLS LAST, comfort DESC", label: "Cleanest air" },
  dirtiest: { sql: "pm25_median DESC NULLS LAST, comfort ASC", label: "Dirtiest air" },
  cities: { sql: "city_count DESC, name", label: "Most cities" },
  name: { sql: "name", label: "A–Z" },
} as const;

export type CountrySort = keyof typeof COUNTRY_SORTS;

export function countrySort(value: string | null | undefined): CountrySort {
  return value && value in COUNTRY_SORTS ? (value as CountrySort) : "sensors";
}

export async function listCountries(sort: CountrySort = "sensors"): Promise<CountryRow[]> {
  const { results } = await DB()
    .prepare(`SELECT * FROM countries ORDER BY ${COUNTRY_SORTS[sort].sql}`)
    .all<CountryRow>();
  return results ?? [];
}

/**
 * A country's cities. Sensor cities first, then by comfort, then by size.
 *
 * The last term used to be a position with no number behind it; since the GeoNames merge `rank` is
 * ordered by real population, so the tail of a long list is the largest towns rather than whatever
 * the source happened to emit first. That is what makes truncating at a few hundred honest.
 */
export async function getCitiesInCountry(countryId: number, limit = 200): Promise<CityRow[]> {
  const { results } = await DB()
    .prepare(
      `SELECT c.*, co.slug AS country_slug, co.name AS country
         FROM cities c JOIN countries co ON co.id = c.country_id
        WHERE c.country_id = ?1
        ORDER BY (c.station_count = 0), (c.comfort IS NULL), c.comfort DESC, c.rank
        LIMIT ?2`,
    )
    .bind(countryId, limit)
    .all<CityRow>();
  return results ?? [];
}

// ── cities ──────────────────────────────────────────────────────────────────

/**
 * Every city query selects through this.
 *
 * `country` and `country_slug` are joined in rather than stored on the row, which is the whole
 * point of the countries table: there is one spelling of "Turkey" in the database and one place
 * that owns it. The join is an indexed integer key and adds no query — the city page still costs
 * the same four round trips it always did.
 */
const CITY_SELECT = `
  SELECT c.*, co.slug AS country_slug, co.name AS country
    FROM cities c JOIN countries co ON co.id = c.country_id`;

/**
 * What makes a city rankable. Written once because the count printed beside a list has to agree
 * with the list — "showing the first 150 of 1 312" is a lie the moment these two drift apart.
 */
const RANKABLE = "c.comfort IS NOT NULL AND c.station_count > 0";

/**
 * How many devices before a city's number is a measurement rather than a sample.
 *
 * Three is a judgement, and here is the arithmetic behind it: 420 of the 904 scored cities have
 * exactly one device, and 587 have fewer than three. A single fifty-euro sensor on one balcony is
 * a reading about that balcony — it can sit beside a road, above a chimney, or in the sun, and
 * nothing in the data says which. With three there is a median, and a median of three survives one
 * of them being wrong.
 *
 * They keep their pages. They are only kept out of a *league table*, which is the one place a
 * number gets read as a comparison.
 */
export const RANK_MIN_SENSORS = 3;

export async function getCity(countrySlug: string, citySlug: string): Promise<CityRow | null> {
  return await DB()
    .prepare(`${CITY_SELECT} WHERE co.slug = ?1 AND c.slug = ?2`)
    .bind(slug(countrySlug), slug(citySlug))
    .first<CityRow>();
}

export async function getCityById(id: number): Promise<CityRow | null> {
  return await DB().prepare(`${CITY_SELECT} WHERE c.id = ?1`).bind(id).first<CityRow>();
}

/** Thirty days of daily aggregates, oldest first — the shape the chart wants. */
export async function getCityHistory(cityId: number, days = 30): Promise<DayPoint[]> {
  const { results } = await DB()
    .prepare(
      `SELECT day, comfort, pm25, temp, uv
         FROM city_daily
        WHERE city_id = ?1
        ORDER BY day DESC
        LIMIT ?2`,
    )
    .bind(cityId, days)
    .all<DayPoint>();
  return (results ?? []).reverse();
}

/**
 * Cities near a point, for the "nearby" rail. Bounded by a lat/lon box first so SQLite can use
 * the geo index; the exact distance ordering happens on the handful of rows that survive.
 */
export async function getNearbyCities(
  lat: number,
  lon: number,
  degrees = 2,
  limit = 6,
  excludeId?: number,
): Promise<CityRow[]> {
  const { results } = await DB()
    .prepare(
      `${CITY_SELECT}
        WHERE c.lat BETWEEN ?1 - ?3 AND ?1 + ?3
          AND c.lon BETWEEN ?2 - ?3 AND ?2 + ?3
          AND c.id != ?5
        ORDER BY (c.lat - ?1) * (c.lat - ?1) + (c.lon - ?2) * (c.lon - ?2)
        LIMIT ?4`,
    )
    .bind(lat, lon, degrees, limit, excludeId ?? -1)
    .all<CityRow>();
  return results ?? [];
}

/**
 * Search, by city name or by device id.
 *
 * Two questions arrive through one box because a reader does not know which they are asking. "sofia"
 * is a place; "82613" is a number printed on a box in someone's garden, and the person typing it is
 * usually its owner. Answering both from one field costs one extra query and saves explaining the
 * difference.
 *
 * Ordering is by size, not alphabetical: ten thousand cities contain a great many hamlets called
 * Springfield, and the one the reader meant is almost always the big one. `rank` is the position in
 * the source's population-ordered list, so it ascends — 0 is the largest city in its country. Places
 * with sensors are lifted above places without, because those are the pages with something to show.
 *
 * `LIKE 'q%'` uses the name index; `LIKE '%q%'` cannot, and on this table that is a full scan on
 * every keystroke. So a prefix match is the first pass and the contains-match is the fallback,
 * merged here rather than in SQL so the prefix hits always sort first.
 */
export interface SearchHit {
  kind: "city" | "station";
  id: number;
  name: string;
  detail: string;
  path: string;
  pm25: number | null;
  comfort: number | null;
}

export async function search(query: string, limit = 8): Promise<SearchHit[]> {
  const q = query.trim();
  if (q.length < 2) return [];

  const hits: SearchHit[] = [];

  // A bare number is a device id, and the reader wants that device — not the town whose name
  // happens to contain digits. Looked up first so it lands at the top.
  if (/^\d{2,7}$/.test(q)) {
    const station = await DB()
      .prepare(
        `SELECT s.id, s.pm25, s.sensor_type, c.name AS city_name, c.slug AS city_slug,
                co.slug AS country_slug
           FROM stations s
           LEFT JOIN cities c ON c.id = s.city_id
           LEFT JOIN countries co ON co.id = c.country_id
          WHERE s.id = ?1`,
      )
      .bind(Number(q))
      .first<{
        id: number;
        pm25: number | null;
        sensor_type: string | null;
        city_name: string | null;
        city_slug: string | null;
        country_slug: string | null;
      }>();

    if (station?.country_slug && station.city_slug) {
      hits.push({
        kind: "station",
        id: station.id,
        name: `Station ${station.id}`,
        detail: [station.city_name, station.sensor_type?.toUpperCase()].filter(Boolean).join(" · "),
        path: paths.station(station.country_slug, station.city_slug, station.id),
        pm25: station.pm25,
        comfort: null,
      });
    }
  }

  const like = q.replace(/[%_]/g, "");
  const { results } = await DB()
    .prepare(
      `${CITY_SELECT}
        WHERE c.name LIKE ?1 OR c.name LIKE ?2
        ORDER BY (c.name LIKE ?1) DESC,
                 (c.station_count > 0) DESC,
                 c.rank ASC
        LIMIT ?3`,
    )
    .bind(`${like}%`, `%${like}%`, limit)
    .all<CityRow>();

  for (const c of results ?? []) {
    hits.push({
      kind: "city",
      id: c.id,
      name: c.name,
      detail:
        c.country +
        (c.station_count > 0
          ? ` · ${c.station_count} sensor${c.station_count === 1 ? "" : "s"}`
          : " · modelled"),
      path: paths.city(c.country_slug, c.slug),
      pm25: c.pm25_median,
      comfort: c.comfort,
    });
  }

  return hits.slice(0, limit);
}

/**
 * Every city with a device, best comfort first — the ranking page.
 *
 * Deliberately not `getCityAggregates`: that one feeds the map and must stay lean, and adding the
 * signal blob to it would put ten thousand copies of a JSON string into a GeoJSON response for the
 * sake of a list nobody is looking at from the map.
 */
/**
 * How a list can be ordered.
 *
 * A ranking that only shows the best is half a ranking. Someone comparing three towns before
 * deciding where to spend a winter wants the bottom as much as the top, and someone who lives in
 * the bottom one wants to find it. The orders live here rather than in the page because the country
 * list needs the same set, and because a sort key arriving from a query string must never reach
 * SQL — this map is the allow-list that makes that impossible.
 */
export const CITY_SORTS = {
  best: { sql: "c.comfort DESC, c.station_count DESC", label: "Most comfortable" },
  worst: { sql: "c.comfort ASC, c.station_count DESC", label: "Least comfortable" },
  cleanest: { sql: "c.pm25_median ASC, c.comfort DESC", label: "Cleanest air" },
  dirtiest: { sql: "c.pm25_median DESC, c.comfort ASC", label: "Dirtiest air" },
  sensors: { sql: "c.station_count DESC, c.comfort DESC", label: "Most sensors" },
} as const;

export type CitySort = keyof typeof CITY_SORTS;

/** Whatever arrived, narrowed to something safe — an unknown key is the default, never an error. */
export function citySort(value: string | null | undefined): CitySort {
  return value && value in CITY_SORTS ? (value as CitySort) : "best";
}

export async function getRankedCities(
  limit = 200,
  sort: CitySort = "best",
  minSensors = RANK_MIN_SENSORS,
): Promise<CityRow[]> {
  // `pm25_median` can be NULL on a city whose devices all went quiet, and NULLs sort first in
  // SQLite — which would open "cleanest air" with a list of cities that have no reading at all.
  const nullsLast = sort === "cleanest" ? " AND c.pm25_median IS NOT NULL" : "";
  const { results } = await DB()
    .prepare(
      `${CITY_SELECT} WHERE ${RANKABLE}${nullsLast} AND c.station_count >= ?2
        ORDER BY ${CITY_SORTS[sort].sql} LIMIT ?1`,
    )
    .bind(limit, minSensors)
    .all<CityRow>();
  return results ?? [];
}

/** How many cities clear the bar, and how many are being held back by it. */
export async function countRankable(): Promise<{ eligible: number; thin: number }> {
  const row = await DB()
    .prepare(
      `SELECT SUM(c.station_count >= ?1) AS eligible, SUM(c.station_count < ?1) AS thin
         FROM cities c WHERE ${RANKABLE}`,
    )
    .bind(RANK_MIN_SENSORS)
    .first<{ eligible: number; thin: number }>();
  return { eligible: row?.eligible ?? 0, thin: row?.thin ?? 0 };
}

/** How many cities have a device at all — the total behind a truncated ranking. */
export async function countCitiesWithSensors(): Promise<number> {
  const row = await DB()
    .prepare(`SELECT COUNT(*) AS n FROM cities c WHERE ${RANKABLE}`)
    .first<{ n: number }>();
  return row?.n ?? 0;
}

/** Best and worst comfort today, for the home page. One query, not two passes. */
export async function getComfortExtremes(limit = 6): Promise<{ best: CityRow[]; worst: CityRow[] }> {
  const [best, worst] = await DB().batch<CityRow>([
    DB()
      .prepare(
        `${CITY_SELECT} WHERE ${RANKABLE} ORDER BY c.comfort DESC LIMIT ?1`,
      )
      .bind(limit),
    DB()
      .prepare(
        `${CITY_SELECT} WHERE ${RANKABLE} ORDER BY c.comfort ASC LIMIT ?1`,
      )
      .bind(limit),
  ]);
  return { best: best.results ?? [], worst: worst.results ?? [] };
}

/**
 * Store what a page just computed, so the next visitor does not compute it again.
 *
 * This is the one place the Worker writes, and the boundary is deliberate: it may fill the *cache*
 * columns of a row that already exists — the readings, the scores, the timestamp — and nothing
 * else. Cities and stations are created only by the ETL, so a bad request cannot invent a page or
 * change what the site is about. `ARCHITECTURE.md` states the rule; this function is its whole
 * surface.
 *
 * Called from `ctx.waitUntil`, so it never delays the response that produced the data.
 */
export async function saveCityReadings(
  cityId: number,
  data: {
    comfort: number;
    worstSignal: string | null;
    signals: Record<string, number>;
    readings: Record<string, number>;
  },
): Promise<void> {
  await DB()
    .prepare(
      `UPDATE cities
          SET comfort = ?2, worst_signal = ?3, signals_json = ?4, readings_json = ?5,
              updated_at = ?6
        WHERE id = ?1`,
    )
    .bind(
      cityId,
      data.comfort,
      data.worstSignal,
      JSON.stringify(data.signals),
      JSON.stringify(data.readings),
      new Date().toISOString(),
    )
    .run();
}

// ── stations ────────────────────────────────────────────────────────────────

export async function getStation(id: number): Promise<StationRow | null> {
  return await DB().prepare("SELECT * FROM stations WHERE id = ?1").bind(id).first<StationRow>();
}

/** The devices a city's numbers were computed from, worst reading first. */
export async function getStationsForCity(cityId: number, limit = 60): Promise<StationRow[]> {
  const { results } = await DB()
    .prepare(
      `SELECT * FROM stations
        WHERE city_id = ?1
        ORDER BY (last_seen IS NULL), pm25 DESC
        LIMIT ?2`,
    )
    .bind(cityId, limit)
    .all<StationRow>();
  return results ?? [];
}

/**
 * The devices closest to a point, nearest first.
 *
 * Distinct from `getStationsForCity`, which orders by reading because a city page is asking "who
 * is dirtiest". A station page's "nearest stations" panel is asking a different question, and was
 * being answered with the dirtiest — a heading saying one thing over a list showing another.
 *
 * Squared degrees is a coarse pre-filter, not the answer: a degree of longitude is two thirds of a
 * degree of latitude at 49°, so this ordering is distorted. It exists to let an index cut the city
 * down to a handful of candidates — the caller then sorts those by real distance. Hence the
 * `overFetch`: ask for more than you will show.
 */
export async function getNearestStations(
  cityId: number,
  lat: number,
  lon: number,
  limit = 4,
  excludeId?: number,
  overFetch = 4,
): Promise<StationRow[]> {
  const { results } = await DB()
    .prepare(
      `SELECT * FROM stations
        WHERE city_id = ?1 AND id != ?5
        ORDER BY (lat - ?2) * (lat - ?2) + (lon - ?3) * (lon - ?3)
        LIMIT ?4`,
    )
    .bind(cityId, lat, lon, limit * overFetch, excludeId ?? -1)
    .all<StationRow>();
  return results ?? [];
}

export async function getStationHistory(
  stationId: number,
  days = 30,
): Promise<{ day: string; pm25: number | null; pm10: number | null }[]> {
  const { results } = await DB()
    .prepare(
      `SELECT day, pm25, pm10 FROM readings_daily
        WHERE station_id = ?1
        ORDER BY day DESC LIMIT ?2`,
    )
    .bind(stationId, days)
    .all<{ day: string; pm25: number | null; pm10: number | null }>();
  return (results ?? []).reverse();
}


// ── map layers ──────────────────────────────────────────────────────────────

/** Zoom < 8: one dot per city, sized by device count. Only cities that actually have devices. */
export async function getCityAggregates(): Promise<
  { id: number; name: string; country_slug: string; slug: string; lat: number; lon: number; station_count: number; pm25_median: number | null; comfort: number | null }[]
> {
  const { results } = await DB()
    .prepare(
      `SELECT c.id, c.name, co.slug AS country_slug, c.slug, c.lat, c.lon,
              c.station_count, c.pm25_median, c.comfort
         FROM cities c JOIN countries co ON co.id = c.country_id
        WHERE c.station_count > 0`,
    )
    .all<any>();
  return results ?? [];
}

/** The densest cities, for the map's rail. Sorted by the database, not by the page. */
export async function getTopSensorCities(limit = 60): Promise<
  { id: number; name: string; country_slug: string; slug: string; station_count: number; pm25_median: number | null; comfort: number | null }[]
> {
  const { results } = await DB()
    .prepare(
      `SELECT c.id, c.name, co.slug AS country_slug, c.slug, c.station_count, c.pm25_median, c.comfort
         FROM cities c JOIN countries co ON co.id = c.country_id
        WHERE c.station_count > 0
        ORDER BY c.station_count DESC
        LIMIT ?1`,
    )
    .bind(limit)
    .all<any>();
  return results ?? [];
}

/**
 * Zoom >= 8: the devices themselves. `bbox` is honoured when given; without it the whole set comes
 * back, which at ~9 000 rows is a 400 KB response the edge caches — cheaper than a query per pan.
 */
export async function getStationPoints(
  bbox?: [number, number, number, number],
): Promise<
  {
    id: number;
    lat: number;
    lon: number;
    pm25: number | null;
    last_seen: string | null;
    sensor_type: string | null;
    city_name: string | null;
    country_slug: string | null;
    city_slug: string | null;
  }[]
> {
  // Joined so a pin can carry its own URL. A marker you can click but not open is a marker that
  // does nothing, and building the path in the browser would need a second lookup per pin.
  const base = `
    SELECT s.id, s.lat, s.lon, s.pm25, s.last_seen, s.sensor_type,
           c.name AS city_name, co.slug AS country_slug, c.slug AS city_slug
      FROM stations s
      LEFT JOIN cities c     ON c.id  = s.city_id
      LEFT JOIN countries co ON co.id = c.country_id`;
  const stmt = bbox
    ? DB()
        .prepare(`${base} WHERE s.lat BETWEEN ?1 AND ?3 AND s.lon BETWEEN ?2 AND ?4`)
        .bind(bbox[1], bbox[0], bbox[3], bbox[2])
    : DB().prepare(base);
  const { results } = await stmt.all<any>();
  return results ?? [];
}

// ── sitemap ─────────────────────────────────────────────────────────────────

export interface SitemapCounts {
  cities: number;
  citiesIndexable: number;
  stations: number;
  stationsIndexable: number;
}

/** Both totals, so the sitemap route can log what it dropped instead of truncating in silence. */
export async function getSitemapCounts(): Promise<SitemapCounts> {
  const row = await DB()
    .prepare(
      `SELECT
         (SELECT COUNT(*) FROM cities)                      AS cities,
         (SELECT COUNT(*) FROM cities   WHERE indexable = 1) AS citiesIndexable,
         (SELECT COUNT(*) FROM stations)                     AS stations,
         (SELECT COUNT(*) FROM stations WHERE indexable = 1) AS stationsIndexable`,
    )
    .first<SitemapCounts>();
  return row ?? { cities: 0, citiesIndexable: 0, stations: 0, stationsIndexable: 0 };
}

export async function listIndexableCities(
  offset: number,
  limit: number,
): Promise<{ country_slug: string; slug: string; updated_at: string | null }[]> {
  const { results } = await DB()
    .prepare(
      `SELECT co.slug AS country_slug, c.slug, c.updated_at
         FROM cities c JOIN countries co ON co.id = c.country_id
        WHERE c.indexable = 1 ORDER BY c.id LIMIT ?1 OFFSET ?2`,
    )
    .bind(limit, offset)
    .all<any>();
  return results ?? [];
}

export async function listIndexableStations(
  offset: number,
  limit: number,
): Promise<{ id: number; country_slug: string; slug: string; last_seen: string | null }[]> {
  const { results } = await DB()
    .prepare(
      `SELECT s.id, co.slug AS country_slug, c.slug, s.last_seen
         FROM stations s
         JOIN cities c    ON c.id  = s.city_id
         JOIN countries co ON co.id = c.country_id
        WHERE s.indexable = 1 ORDER BY s.id LIMIT ?1 OFFSET ?2`,
    )
    .bind(limit, offset)
    .all<any>();
  return results ?? [];
}

// ── freshness ───────────────────────────────────────────────────────────────

/**
 * When the data was last refreshed. A page that is showing yesterday's numbers should say so
 * rather than imply it is live — the product's entire claim is about what is true right now.
 */
export async function getLastIngest(): Promise<Date | null> {
  const row = await DB()
    .prepare("SELECT value FROM meta WHERE key = 'last_ingest_at'")
    .first<{ value: string }>();
  const t = row?.value ? Date.parse(row.value) : NaN;
  return Number.isFinite(t) ? new Date(t) : null;
}

export interface SourceRow {
  id: number;
  city_id: number;
  osm_id: string;
  name: string;
  kind: "power_plant" | "works" | "industrial" | "motorway" | "trunk";
  lat: number;
  lon: number;
  distance_km: number;
  bearing_deg: number | null;
}

/**
 * What is upwind, from OpenStreetMap.
 *
 * Ordered by distance because that is the order they matter in, and capped because a city can sit
 * inside a ring of forty industrial parcels and a map with forty labels on it says nothing. Roads
 * come last on a tie: a motorway is a real source and also the least surprising one.
 */
export async function getSources(cityId: number, limit = 24): Promise<SourceRow[]> {
  const { results } = await DB()
    .prepare(
      `SELECT * FROM sources
        WHERE city_id = ?1
        ORDER BY (kind IN ('motorway','trunk')), distance_km
        LIMIT ?2`,
    )
    .bind(cityId, limit)
    .all<SourceRow>();
  return results ?? [];
}

export interface CpfRow {
  source_id: number;
  name: string;
  kind: SourceRow["kind"];
  distance_km: number;
  score: number;
  bearing_deg: number;
  hours: number;
  high_hours: number;
  pm25_from: number | null;
  pm25_other: number | null;
  period: string | null;
  /** How many mapped sites share this bearing, including the one named. */
  others: number;
}

/**
 * Which direction this city's dirtiest hours blew from, one row per direction.
 *
 * Filtered to sources that clear their own background: one whose downwind average matches every
 * other direction has not been shown to do anything, and printing it with a number beside it would
 * read as an accusation the data does not make.
 *
 * Grouped by bearing, which is not a presentation detail. The method compares a fifteen-degree
 * sector against everything else, so every site on that bearing gets the *same* score by
 * construction — Heilbronn returned three factories with an identical 76 %, 4.9 against 2.3, over
 * the same 25 hours. Listing them separately implies three findings where there is one, and the
 * repetition reads as a bug. One row per thirty-degree sector, named after the nearest site in it,
 * with the rest counted.
 */
export async function getCpf(cityId: number, limit = 5): Promise<CpfRow[]> {
  const { results } = await DB()
    .prepare(
      `WITH scored AS (
         SELECT s.id AS source_id, s.name, s.kind, s.distance_km,
                c.score, c.bearing_deg, c.hours, c.high_hours,
                c.pm25_from, c.pm25_other, c.period,
                CAST(c.bearing_deg / 30 AS INTEGER) AS sector,
                ROW_NUMBER() OVER (
                  PARTITION BY CAST(c.bearing_deg / 30 AS INTEGER)
                  -- The nearest site names the sector, and a works outranks a road at equal
                  -- distance: the road is the least surprising thing on any bearing.
                  ORDER BY (s.kind IN ('motorway','trunk')), s.distance_km
                ) AS r,
                COUNT(*) OVER (PARTITION BY CAST(c.bearing_deg / 30 AS INTEGER)) AS n
           FROM cpf c JOIN sources s ON s.id = c.source_id
          WHERE c.city_id = ?1
            AND c.pm25_from > c.pm25_other * 1.15
       )
       SELECT source_id, name, kind, distance_km, score, bearing_deg,
              hours, high_hours, pm25_from, pm25_other, period, n AS others
         FROM scored
        WHERE r = 1
        ORDER BY score DESC, pm25_from DESC
        LIMIT ?2`,
    )
    .bind(cityId, limit)
    .all<CpfRow>();
  return results ?? [];
}
