/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const wasm_aqi_category: (a: number) => [number, number];
export const wasm_classify_source: (a: number, b: number) => [number, number];
export const wasm_comfort_score: (a: number, b: number) => [number, number];
export const wasm_feature_names: () => [number, number];
export const wasm_geomagnetic: (a: number) => [number, number];
export const wasm_matrix_latest: (a: number, b: number) => [number, number];
export const wasm_matrix_ml_vector: (a: number, b: number) => [number, number];
export const wasm_matrix_push: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const wasm_matrix_slice: (a: number, b: number, c: number) => [number, number];
export const wasm_matrix_summary: (a: number, b: number) => [number, number];
export const wasm_merge: (a: number, b: number) => [number, number];
export const wasm_moon_phase: (a: number, b: number, c: number) => number;
export const wasm_normalize_daylight: (a: number) => number;
export const wasm_normalize_earthquake: (a: number) => number;
export const wasm_normalize_fire: (a: number) => number;
export const wasm_normalize_geomagnetic: (a: number) => number;
export const wasm_normalize_humidity: (a: number) => number;
export const wasm_normalize_marine: (a: number) => number;
export const wasm_normalize_moon: (a: number) => number;
export const wasm_normalize_noise: (a: number) => number;
export const wasm_normalize_pollen: (a: number) => number;
export const wasm_normalize_temperature: (a: number) => number;
export const wasm_normalize_uv: (a: number) => number;
export const wasm_normalize_wind: (a: number) => number;
export const wasm_overall_aqi: (a: number, b: number) => number;
export const wasm_pollen_status: (a: number, b: number) => [number, number];
export const wasm_pollutant_status: (a: number, b: number, c: number) => [number, number];
export const wasm_progress_bar: (a: number) => [number, number];
export const wasm_signal_comfort: (a: number, b: number) => [number, number];
export const wasm_signal_vector: (a: number, b: number) => [number, number];
export const wasm_signal_weights: () => [number, number];
export const wasm_wind_direction: (a: number) => [number, number];
export const wasm_normalize_air: (a: number) => number;
export const wasm_haversine: (a: number, b: number, c: number, d: number) => number;
export const wasm_normalize_pressure: (a: number, b: number) => number;
export const wasm_signal_names: () => [number, number];
export const wasm_pm10_aqi: (a: number) => number;
export const wasm_pm25_aqi: (a: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_start: () => void;
